import { ShoppingBag, Truck, CarFront, Plus } from 'lucide-react';
import SectionHeading from './SectionHeading';
const pillars = [
  { name: 'Market', icon: ShoppingBag, tag: 'COMERCIO', subtitle: 'El barrio. En tu bolsillo.', description: 'Ofertas, combos y remates de comercios locales, reunidos en un marketplace pensado para descubrir y comprar cerca.', details: 'Catálogo local, promociones por comercio y un recorrido de compra conectado con la entrega. El alcance inicial se validará durante el piloto.', tone: 'cyan' },
  { name: 'Logistics', icon: Truck, tag: 'SUMO ENVÍOS', subtitle: 'La última milla, resuelta.', description: 'Una red de logística regional que conecta cada pedido con su destino y acompaña la operación de los comercios.', details: 'Sumo Envíos será la vertical de coordinación de entregas, con trazabilidad y cobertura a definir por zona durante el piloto.', tone: 'green' },
  { name: 'Move', icon: CarFront, tag: 'MOVILIDAD', subtitle: 'Tu próximo destino, más cerca.', description: 'Traslados bajo demanda integrados al ecosistema: una experiencia simple para moverse por la ciudad.', details: 'La implementación contempla validar la oferta de conductores, la experiencia de reserva y los requisitos operativos de cada jurisdicción.', tone: 'violet' },
];
export default function Ecosystem() {
  return <section id="ecosistema" className="section section-tinted"><div className="container"><SectionHeading number="02" eyebrow="UN ECOSISTEMA, TRES MOTORES" title={<>Todo lo que mueve a la región.<br /><span className="muted">Ahora, conectado.</span></>} /><div className="grid gap-5 lg:grid-cols-3">{pillars.map(({ name, icon: Icon, tag, subtitle, description, details, tone }, i) => <article className={`pillar ${tone}`} key={name}><div className="flex items-center justify-between"><span className="pillar-icon"><Icon size={26} /></span><span className="micro">0{i + 1} / {tag}</span></div><h3>AXO <span>{name}</span></h3><h4>{subtitle}</h4><p>{description}</p><details><summary>Explorar la propuesta<Plus size={17} /></summary><p>{details}</p></details></article>)}</div><p className="ecosystem-caption">Una misma visión: más oportunidades para comprar, vender y moverse cerca.</p></div></section>;
}
